# Generated by Django 5.1.2 on 2025-02-17 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('environment', models.CharField(max_length=255)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'event_outbox',
                'ordering': ['id'],
            },
        ),
    ]
